---
development:
  adapter: mysql2
  database: kilo_development
  host: <%= ENV['MYSQL_HOSTNAME'] %>
  port: 3306
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 50

test:
  adapter: mysql2
  database: kilo_test
  host: <%= ENV['MYSQL_HOSTNAME'] %>
  port: 3306
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 5

production:
  adapter: mysql2
  database: kilo_production
  host: <%= ENV['MYSQL_HOSTNAME'] %>
  port: 3306
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 50
